# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  sdraw_config = debug

else ifeq ($(config),release)
  sdraw_config = release

else ifeq ($(config),mingw)
  sdraw_config = mingw

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := sdraw

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

sdraw:
ifneq (,$(sdraw_config))
	@echo "==== Building sdraw ($(sdraw_config)) ===="
	@${MAKE} --no-print-directory -C . -f sdraw.make config=$(sdraw_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f sdraw.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  mingw"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   sdraw"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"